### ISSUE TITLE
Programmatic import resolution

### ISSUE THREAD

**Issue by titzer** [rossberg/wasm-c-api#53]
In the proposed API, the creating of an instance (`Instance::make()`) takes an array of imports. Presumably, this array positionally corresponds to the imports declared for a module. As such, the declared module and import names within the module would be ignored. I think we should change this API to allow the instantiator to supply an implementation of class that does import resolution, something along the lines of (roughly):

class ImportResolver {
  const Memory* resolveMemory(const char* module_name, const char* import_name);
  const Func* resolveFunc(const char* module_name, const char* import_name);
  . . .
}

**Comment by rossberg** [comment]
The current design is intentional. I think it is crucial to avoid making the basic interface higher-order, since that would be very inconvenient to map to plain C and even harder (and likely more costly) to access from FFI bindings.

The interface you propose can be implemented very easily on top of what's currently provided, but not vice versa.

(Also, there are valid use cases where it is simpler to treat imports/exports positionally and not having to care about their names at all, see e.g. the examples. Basically, whenever you are in control of the binary.)

**Comment by titzer** [comment]
The problem is that positional correspondence does not provide the embedder enough information to resolve imports at all, except by convention or out-of-band information such as parsing the imports itself. Names, kinds, and signatures are the language of imports, so a complete API needs to expose them.

(And about layering, you actually cannot implement named import resolution on top of positional correspondence without out-of-band information, whereas the opposite is easy if the contract is to request imports through the programmatic interface in import order).

**Comment by titzer** [comment]
Actually, sorry. Now that I look at it, I guess it is possible to extract the imports from the module itself and then do the lookups programmaticallly.

**Comment by rossberg** [comment]
Yes, that was the idea.
